ORG 0x0000   

CLR A
CLR C
MOV R1, #0A0H         ; HIGH PART OF DIVIDENT
MOV R0, #15H         ; LOW PART OF DIVIDENT
MOV R2, #70H     ; DIVISOR
MOV R7, A   ; R7=0H, HIGH PART OF QUOTIENT
MOV R6, A   ; R6=0H, LOW PART OF QUOTIENT
MOV R5, A   ; REMAINDER
MOV A, R1	;FIRST DIVIDE HIGH BYTE BY DIVISOR SO WE CAN DECREASE NUMBER OF OPERATIONS
MOV B, R2
DIV AB
MOV R7, A
MOV R1, B
LOOP:
	MOV A, R0
	SUBB A, R2
	MOV R0, A
	JNC NOPROBLEM
	MOV A, R1
	SUBB A, #0
	MOV R1, A
	JC FINISH
	NOPROBLEM:
	INC R6
	SJMP LOOP
FINISH: MOV A,R0
	ADD A, R2
	MOV R5,A
HERE: SJMP HERE
end
